version: '3.8'

services:
  app:
    build: .
    container_name: domdarom-app
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=club_db
      - DB_USER=darlabayandina
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=3000
      - NODE_ENV=production
      - YANDEX_EMAIL=${YANDEX_EMAIL}
      - YANDEX_APP_PASSWORD=${YANDEX_APP_PASSWORD}
    network_mode: "host"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped