version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_DB: club_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: securepassword12
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d club_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: domdarom-app
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - DB_HOST=db 
      - DB_PORT=5432
      - DB_NAME=club_db
      - DB_USER=myuser
      - DB_PASSWORD=securepassword12
      - PORT=3000
      - NODE_ENV=production
      - YANDEX_EMAIL=${YANDEX_EMAIL}
      - YANDEX_APP_PASSWORD=${YANDEX_APP_PASSWORD}
      - VIRTUAL_HOST=api.domdarom.me
      - YOOKASSA_SHOP_ID=510835
      - YOOKASSA_SECRET_KEY=test_*gSZ1sNXvXEHTBi3DffHTncFsJwS-afkEp1Sdiri9jE3g
      - FRONTEND_URL=https://domdarom.me
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge