version: '3.8'

services:
  app:
    build: .
    container_name: domdarom-app
    ports:
      - "3000:3000"  # 🔥 Пробрасываем порт
    environment:
      - DB_HOST=host.docker.internal  # 🔥 Специальное имя для доступа к хосту
      - DB_PORT=5432
      - DB_NAME=club_db
      - DB_USER=dariabayandina
      - DB_PASSWORD=1234
      - PORT=3000
      - NODE_ENV=production
      - YANDEX_EMAIL=d0mdarom@yandex.ru
      - YANDEX_APP_PASSWORD=omsjbmtbawyxdpxm
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 🔥 Для доступа к localhost хоста
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped